/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lwm_javacallc_JNITest */

#ifndef _Included_com_lwm_javacallc_JNITest
#define _Included_com_lwm_javacallc_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lwm_javacallc_JNITest
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_lwm_javacallc_JNITest_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_lwm_javacallc_JNITest
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lwm_javacallc_JNITest_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_lwm_javacallc_JNITest
 * Method:    increaseArrayEles
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_lwm_javacallc_JNITest_increaseArrayEles
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_lwm_javacallc_JNITest
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_lwm_javacallc_JNITest_checkPwd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
